AWSTemplateFormatVersion: 2010-09-09
Description: Codepipeline pre requisites

Resources:
  S3ArtifactsBucketjm:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub jhonmora-codepipeline-artefactos-${AWS::AccountId}-${AWS::Region}

  S3ArtifactsBucketPolicyjm:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ArtifactsBucketjm
      PolicyDocument:
        Version: "2012-10-17"
        Id: SSEAndSSLPolicy
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt CodeBuildRolejm.Arn
                - !GetAtt CodePipelineRolejm.Arn
            Action:
              - s3:Get*
              - s3:Put*
            Resource: !Sub "arn:aws:s3:::${S3ArtifactsBucketjm}/*"

  CodeBuildRolejm:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/service-role/"
      Policies:
        - PolicyName: codebuild-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                  - ec2:CreateNetworkInterfacePermission
                  - lambda:*
                  - cloudformation:Describe*
                  - cloudformation:Get*
                  - cloudformation:List*
                  - cloudformation:ValidateTemplate
                  - cloudformation:ExecuteChangeSet
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                  - sqs:*
                  - sns:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*

  CodePipelineRolejm:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: codepipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub "arn:aws:s3:::${S3ArtifactsBucketjm}/*"
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetProjects
                  - codebuild:ListBuilds
                  - codebuild:ListBuildsForProject
                  - codebuild:ListConnectedOAuthAccounts
                  - codebuild:ListProjects
                  - codebuild:ListRepositories
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - sns:Publish
                  - cloudwatch:*
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                  - s3:*
                  - iam:PassRole
                  - cloudformation:*
                Resource: "*"

  LambdaPolicyEC2jhonmora:
      Type: AWS::IAM::ManagedPolicy
      Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                  -
                    Effect: Allow
                    Action:
                        - ec2:DisassociateAddress
                        - ec2:CreateDhcpOptions
                        - ec2:ReplaceRouteTableAssociation
                        - ec2:RunScheduledInstances
                        - ec2:RequestSpotFleet
                        - ec2:DisableVgwRoutePropagation
                        - ec2:AssociateVpcCidrBlock
                        - ec2:ReleaseHosts
                        - ec2:ReplaceRoute
                        - ec2:DisassociateVpcCidrBlock
                        - ec2:DeleteNetworkInterfacePermission
                        - ec2:DescribeNetworkInterfaces
                        - ec2:StartInstances
                        - ec2:DescribeNetworkInterfaceAttribute
                        - ec2:CreateRoute
                        - ec2:ReplaceNetworkAclEntry
                        - ec2:CreateSecurityGroup
                        - ec2:CreateNetworkAcl
                        - ec2:DescribeNetworkInterfacePermissions
                        - ec2:TerminateInstances
                        - ec2:AcceptVpcEndpointConnections
                        - ec2:DeleteNetworkInterface
                        - ec2:CreateRouteTable
                        - ec2:RunInstances
                        - ec2:StopInstances
                        - ec2:DisassociateRouteTable
                        - ec2:DisassociateSubnetCidrBlock
                        - ec2:ModifyHosts
                        - ec2:ReplaceNetworkAclAssociation
                        - ec2:CreateVolume
                        - ec2:CreateNetworkInterface
                        - ec2:DetachVpnGateway
                        - ec2:CreateDefaultVpc
                        - ec2:DisassociateIamInstanceProfile
                        - ec2:CreateVpcEndpoint
                        - ec2:DisableVpcClassicLink
                        - ec2:CreateSubnet
                    Resource:
                        - "*"
  LambdaPolicyDynamojhonmora:
      Type: AWS::IAM::ManagedPolicy
      Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                  -
                    Effect: Allow
                    Action:
                        - dynamodb:PutItem
                        - dynamodb:UpdateItem
                        - dynamodb:GetItem
                        - dynamodb:*
                    Resource:
                        - "*"

  LambdaPolicyCWjhonmora:
      Type: AWS::IAM::ManagedPolicy
      Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                  -
                    Effect: Allow
                    Action:
                        - logs:*
                        - cloudwatch:*
                        - xray:*
                    Resource:
                        - "*"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Ref LambdaPolicyDynamojhonmora
        - !Ref LambdaPolicyEC2jhonmora
        - !Ref LambdaPolicyCWjhonmora
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  LambdaPolicyS3jm:
      Type: AWS::IAM::ManagedPolicy
      Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                  -
                    Effect: Allow
                    Action:
                        - s3:ListAllMyBuckets
                        - s3:HeadBucket
                        - s3:ListObjects
                    Resource:
                        - "*"
                  -
                    Effect: Allow
                    Action:
                        - s3:*
                    Resource:
                        - "*" 



Outputs:
  PipelineRolejm:
    Value: !GetAtt CodePipelineRolejm.Arn
    Export:
      Name: PipelineRolejm
  CodeBuildRolejm:
    Value: !GetAtt CodeBuildRolejm.Arn
    Export:
      Name: CodeBuildRolejm
  S3ArtifactsBucketjm:
    Value: !Ref S3ArtifactsBucketjm
    Export:
      Name: S3ArtifactsBucketjm
  LambdaPolicyDynamojhonmora:
    Value: !Ref LambdaPolicyDynamojhonmora
    Export:
        Name: LambdaPolicyDynamojhonmora
  LambdaPolicyEC2jhonmora:
    Value: !Ref LambdaPolicyEC2jhonmora
    Export:
        Name: LambdaPolicyEC2jhonmora
  LambdaPolicyCWjhonmora:
    Value: !Ref LambdaPolicyCWjhonmora
    Export:
        Name: LambdaPolicyCWjhonmora
  LambdaPolicyS3jm:
    Value: !Ref LambdaPolicyS3jm
    Export:
        Name: LambdaPolicyS3jm        
